version: '3'
services:
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - service1
      - service2
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8182:8080"
