
#--Environment variables----------------------------------------
external-api:
  fixer:
    base-url: ${IPCONSULTING_FIXER_BASE_URL}
  ip-to-country:
    base-url: ${IPCONSULTING_IP_TO_COUNTRY_BASE_URL}
  rest-countries:
    base-url: ${IPCONSULTING_REST_COUNTRIES_BASE_URL}

